services:
  - type: web
    name: profactory-server
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: APP_NAME
        value: "مصنع أقفاص العصافير"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:ld6xo8H/AACNFTL+N88N1ilIDzubxGvJtK4MSCDL//U=
      - key: APP_DEBUG
        value: "false"
      - key: APP_LOCALE
        value: ar
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
